Adds helm charts for server service development, a few crdb debugging notes
metal-toolbox/hollow-serverservice pull request #132
Opened 2022-08-18 10:19 UTC by joelrebel

This adds helm charts used to deploy a development instance of server service along with cockroach db.

2022-08-18 15:45 UTC, joelrebel commented
squash and pushed change with rename of directory - `docs` -> `devel`

2022-08-20 10:42 UTC, matoszz requested changes
@nicolerenee unless you disagree, I don't want to start patterns of coupling the helm chart with the code repo. @joelrebel I'd ask that you move this to it's own repository; it can be in this org or in equinixmetal-helm (preferred)

2022-08-20 10:44 UTC, matoszz commented
@nicolerenee @sfunkhouser don't we also have existing charts for the deployment we're running today?

2022-08-20 11:45 UTC, sfunkhouser commented
> @nicolerenee @sfunkhouser don't we also have existing charts for the deployment we're running today?

Yeah, here: https://github.com/packethost/k8s-delivery-hollow/tree/main/server-service

2022-08-22 07:51 UTC, joelrebel commented
@matoszz the sole purpose of this chart is to enable running a local development instance of Server service

2022-08-23 22:00 UTC, matoszz commented
Yes please @joelrebel

2022-08-24 13:30 UTC, closed without merging