Switch to json.Unmarshal instead of json.Decoder.Decode()
metal-toolbox/hollow-serverservice pull request #174
Opened 2022-12-05 13:45 UTC by joelrebel

This is replaced for a few reasons,

 - The JSON stream decoder blocks forever if the server stops sending data
   midway in the body, see goroutine dump below [0].

 - Switching this to the json.Marshal surfaced issues in implementations where
   multiple JSON blocks were being returned in the response to the client,
    e.g: `{"foo": "bar"}{"foo": "baz"}`
   they are not caught in tests because json.Decoder.Decode doesn't have a problem with those.

 - As of now this service does not stream JSON and if the need arises,
   the implementation could be switched back to the json.Decoder along
   with a for, select loop on the request context.

[0]. Goroutine hung on json.(*Decoder).Decode
```
1 @ 0x43b196 0x44abf2 0x6bf129 0x6be71e 0x46ba21
   0x6bf128    net/http.(*http2clientStream).writeRequest+0x9c8
   /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:8037
   0x6be71d    net/http.(*http2clientStream).doRequest+0x1d
   /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:7899

1 @ 0x43b196 0x467afd 0x467add 0x48024c 0x6a9aab 0x6c5be5 0x56ee5f 0x56ea5b
0x56e798 0xb627dc 0xb60de7 0xb64065 0xcd3f85 0xcd30dc 0xcd2ba5 0xd128fe
0x46ba21
   0x467adc    sync.runtime_notifyListWait+0x11c
   /opt/hostedtoolcache/go/1.18.5/x64/src/runtime/sema.go:513
   0x48024b    sync.(*Cond).Wait+0x8b
   /opt/hostedtoolcache/go/1.18.5/x64/src/sync/cond.go:56
   0x6a9aaa    net/http.(*http2pipe).Read+0xea
   /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:3663
   0x6c5be4    net/http.http2transportResponseBody.Read+0x84
   /opt/hostedtoolcache/go/1.18.5/x64/src/net/http/h2_bundle.go:9098
   0x56ee5e    encoding/json.(*Decoder).refill+0x17e
   /opt/hostedtoolcache/go/1.18.5/x64/src/encoding/json/stream.go:165
   0x56ea5a    encoding/json.(*Decoder).readValue+0xba
   /opt/hostedtoolcache/go/1.18.5/x64/src/encoding/json/stream.go:140
   0x56e797    encoding/json.(*Decoder).Decode+0x77
   /opt/hostedtoolcache/go/1.18.5/x64/src/encoding/json/stream.go:63
```

2022-12-05 14:27 UTC, sfunkhouser approved these changes

2022-12-07 07:17 UTC, JAORMX requested changes

2022-12-07 07:17 UTC, JAORMX commented on pkg/api/v1/errors.go
> +		if err := json.Unmarshal(data, &se); err != nil {
Given this is a change that could easily be regressed, could you add unit tests that ensure that we don't fall back to the previous behavior? I can very easily see that someone is not aware of the Unmarshall/Decode issues and moves back to using a decoder.

2022-12-07 10:14 UTC, JAORMX approved these changes

2022-12-07 10:42 UTC, merged