draft PR with unit test
metal-toolbox/hollow-serverservice pull request #235
Opened 2023-08-23 21:29 UTC by Alva8756

2023-08-24 20:02 UTC, Alva8756 commented
There is an irrelevant test keeps failing the `Linting and Test / lint-and-test` pipeline.
`/hollow-serverservice/pkg/api/v1/router_firmware_test.go:127`
However I can run the test successfully locally.

Wonder if anyone can help me bypass this failure test?

2023-08-29 17:32 UTC, DoctorVin requested changes
This is an impressive bit of work. I left a few comments that I'd like you to address, but nothing really show-stopping. Nice job!

This is marked as `Needs Changes` because it shouldn't be in ServerService (as we discussed earlier). But I think you could lift-and-shift this code to a proxy service and it would be fine.

2023-08-29 17:32 UTC, DoctorVin commented on pkg/api/v1/aoc_mac_address_bom.go
Consider putting all the structs into a single file.

2023-08-29 17:32 UTC, DoctorVin commented on pkg/api/v1/router_bom.go
> +	numDefipwdName string = "NUM-DEFPWD"
I hate bringing up variable names, but I feel like these names don't add much here. Consider `ipmiFieldName` (and likewise `pwdFieldName`)?

2023-08-29 17:32 UTC, DoctorVin commented on pkg/api/v1/router_bom.go
> +					return nil, errors.Errorf("missing colomn, serial num %v, sub-item %v, sub-serial %v", categoryCol.serialNumCol, categoryCol.subItemCol, categoryCol.subSerialCol)
Instead of returning a custom error here, consider using `errors.Wrap` with an exported error and a string of context.

2023-08-29 17:32 UTC, DoctorVin commented on pkg/api/v1/router_bom_test.go
> +				fmt.Println(err)
you have a couple of better (IMO) options here. Consider `t.Logf`, `t.Fatalf` (better, I think) or `require.NoError` (if you are familiar with `github.com/stretchr/testify/require`.

2023-09-01 21:10 UTC, closed without merging